import type { Metadata } from "next";
import "./globals.css";
import Background from "@/components/global/background";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap');
        </style>
      </head>
      <body>
        <Background/>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
