import type { Metadata } from "next";
import "./globals.css";
import "@/css/adaptation.css"
import Background from "@/components/global/background";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  metadataBase: new URL("https://yourdomain.com/"),
  title: {
    default: "Крайтекс XCraiteX | Разработка сайтов, веб-приложений и ботов",
    template: "%s | Разработка сайтов, веб-приложений и ботов",
  },
  description: "Профессиональная разработка сайтов, веб-приложений, Telegram и Discord ботов. Низкие цены, качественная работа.",
  keywords: [
    "разработка сайтов в беларуси",
    "разработка сайтов в россии", 
    "разработка telegram ботов",
    "разработка discord ботов",
    "разработка веб-приложений",
    "xcraitex", "крайтекс",
    "интернет-магазин", "лендинг",
    "многостраничный сайт"
  ],
  authors: [{ name: "XCraiteX" }],
  creator: "XCraiteX",
  publisher: "XCraiteX",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "ru_RU", 
    url: "https://redlite.ru",
    title: "Крайтекс XCraiteX | Разработка сайтов, веб-приложений и ботов",
    description: "Профессиональная разработка сайтов, веб-приложений, Telegram и Discord ботов. Низкие цены, качественная работа.",
    images: [
      {
        url: "/hero-image.jpg",
        width: 1200,
        height: 630,
        alt: "xcraitex logo",
      },
    ],
    siteName: "Крайтекс XCraiteX | Разработка сайтов, веб-приложений и ботов",
  },
  alternates: {
    canonical: "https://redlite.ru",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap');
        </style>
      </head>
      <body>
        <Background/>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
